import React from "react";

const mockOffers = [
  {
    id: "OFF-001",
    title: "5% Cashback on Online Shopping",
    description: "Use your barath Credit Card at top e-commerce sites.",
    validTill: "31 Dec 2025",
    tag: "Cards",
  },
  {
    id: "OFF-002",
    title: "Zero Fee on First UPI AutoPay Setup",
    description: "Set up UPI AutoPay for OTT, utilities, and subscriptions.",
    validTill: "31 Jan 2026",
    tag: "UPI",
  },
  {
    id: "OFF-003",
    title: "Bonus FD Interest +0.25%",
    description: "Get additional interest for FDs above ₹2,00,000.",
    validTill: "15 Jan 2026",
    tag: "Deposits",
  },
];

function OffersPage() {
  return (
    <div style={{ display: "grid", gap: 18 }}>
      <div className="bb-card">
        <div className="bb-card-header">
          <div>
            <div className="bb-card-title">Offers & Rewards</div>
            <div className="bb-card-subtitle">
              Personalized deals based on your spends and banking patterns.
            </div>
          </div>
        </div>
        <div className="bb-card-body grid-3" style={{ gap: 12 }}>
          {mockOffers.map((offer) => (
            <div key={offer.id} className="bb-card mini">
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: 4,
                }}
              >
                <div className="bb-card-title" style={{ fontSize: "0.95rem" }}>
                  {offer.title}
                </div>
                <span className="bb-badge">{offer.tag}</span>
              </div>
              <p
                style={{
                  fontSize: "0.8rem",
                  color: "var(--bb-text-muted)",
                  marginBottom: 6,
                }}
              >
                {offer.description}
              </p>
              <div
                style={{
                  fontSize: "0.75rem",
                  color: "var(--bb-text-muted)",
                }}
              >
                Valid till: {offer.validTill}
              </div>
              <button
                className="bb-button bb-button-secondary"
                style={{ marginTop: 8, fontSize: "0.8rem" }}
                type="button"
                onClick={() =>
                  alert("Demo: Apply offer. Later this will call /api/offers/apply.")
                }
              >
                View Details
              </button>
            </div>
          ))}
        </div>

        <p
          style={{
            fontSize: "0.8rem",
            color: "var(--bb-text-muted)",
            marginTop: 10,
          }}
        >
          In future, this page will fetch personalized offers from{" "}
          <code>/api/offers?customerId=...</code>, potentially generated by an AI
          recommendation engine.
        </p>
      </div>
    </div>
  );
}

export default OffersPage;
